anthology/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story1/', include('story1.urls')),
    path('story4/', include('story4.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story4/urls.py
from django.urls import path

from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.index, name='index'),
    path('extras/', views.extras, name='extras'),
]

story5/urls.py
from django.urls import path

from . import views


app_name = "story5"

urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add_course, name="add_course"),
    path("details/<int:pk>", views.course_details, name="course_details"),
    path("delete/<int:pk>", views.delete_course, name="delete_course"),
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<str:pk>', views.delete_event, name='delete_event'),
    path('delete/member/<str:pk>', views.delete_member, name='delete_member'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Primary Meta Tags -->
  <title>{% block title %}{% endblock %} - Jojo's Anthology</title>
  <link rel="icon" href="{% static 'home/images/j.png' %}">
  
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
</head>
<body>
  {% include "home/navbar.html" %}

  {% block content %}
  {% endblock %}

  {% include "home/footer.html" %}

  <!-- Bootstrap Scripts -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>

home/templates/home/footer-new.html
{% load static %}
<footer class="page-footer font-small">
  <div class="footer-copyright text-center py-3">
    © 2020 Jojo. All Rights Reserved.
  </div>
</footer>

home/templates/home/footer.html
{% load static %}
<footer class="page-footer font-small">
  <div class="footer-copyright text-center py-3">
    © 2020 Jojo. All Rights Reserved.
  </div>
</footer>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}
  <div class="centered">
    <img src="{% static 'home/images/shibainu.png' %}" align="middle" alt="woof woof" width="200" height="200">
    <h3 class="text-center">Welcome!</h3>
    <p class="lead">Click one of the stories on the navbar to begin.</p>
  </div>
{% endblock %}

home/templates/home/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'home/css/style.css' %}">

<nav class="navbar navbar-expand-lg navbar-light fixed-top">
  <a class="navbar-brand" href="/">Jojo's Anthology</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!-- empty-->
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story1:index' %}">Intro</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story4:index' %}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story5:index' %}">Courses</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story6:index' %}">Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story7:index' %}">Accordion</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story8:index' %}">Books</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story9:index' %}">Cookies</a>
      </li>
    </ul>
  </div>
</nav>